# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nytimes-headlines' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nytimes-headlines
  pod 'Alamofire', '~> 4.8.0'
  pod 'Moya', '~> 12.0'
  pod 'SkeletonView'

  target 'nytimes-headlinesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nytimes-headlinesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
